import { CheckCircle2, Clock, MessageSquare, Moon, MoveRight, Pause, Sun, Zap } from "lucide-react";
import { GlassCard, SakaShell, SectionHead, TopBar } from "./_shared/SakaShared";
import "./_group.css";
import { useState } from "react";

const windows = [{ time: "6 AM – 9 AM", name: "Begin gently", note: "Make space before the world asks for your attention.", icon: Sun, color: "var(--saka-gold)" }, { time: "9 AM – 12 PM", name: "Make the move", note: "Best time for important conversations and decisions.", icon: Zap, color: "var(--saka-peach)" }, { time: "12 PM – 3 PM", name: "Connect", note: "Share the draft. Ask the question. Let it be seen.", icon: MessageSquare, color: "var(--saka-mint)" }, { time: "3 PM – 6 PM", name: "Review", note: "Notice what changed after you took action.", icon: CheckCircle2, color: "var(--saka-violet-bright)" }, { time: "6 PM – 9 PM", name: "Reset", note: "Close the loop and come back to yourself.", icon: Moon, color: "var(--saka-rose)" }];
export function DayMap() {
  const [active, setActive] = useState(1);
  const current = windows[active];
  return <SakaShell active="daymap"><TopBar eyebrow="Tuesday · 14 May" title="Today's day map" back /><div className="saka-card saka-card-pad" style={{ paddingBottom: 14 }}><div className="saka-row saka-caption"><span>6 AM</span><span>9 AM</span><span>12 PM</span><span>3 PM</span><span>6 PM</span><span>9 PM</span></div><div style={{ position: "relative", height: 120, marginTop: 13 }}><div style={{ position: "absolute", top: 48, right: 0, left: 0, height: 1, background: "linear-gradient(90deg, rgba(214,169,101,.15), var(--saka-gold), rgba(214,169,101,.15))" }} /><div style={{ position: "absolute", top: 27, left: "36%", width: "25%", height: 60, border: "1px solid rgba(215,169,101,.45)", borderRadius: "9px 9px 2px 2px", background: "linear-gradient(180deg, rgba(183,113,168,.35), rgba(115,72,140,.08))", boxShadow: "0 0 30px rgba(170,96,176,.2)" }} /><svg width="100%" height="100%" viewBox="0 0 340 120" style={{ position: "absolute", inset: 0 }}><path d="M0 70 C30 59 50 74 78 63 S122 43 147 55 S192 70 218 42 S261 22 287 48 S321 68 340 49" fill="none" stroke="#d2a1c4" strokeWidth="1.6" /></svg><div style={{ position: "absolute", top: 20, left: "48%", width: 8, height: 8, borderRadius: "50%", background: "var(--saka-gold)", boxShadow: "0 0 11px var(--saka-gold)" }} /></div><div className="saka-row saka-caption"><span>LOW</span><span>ATTENTION</span><span>HIGH</span></div></div>
    <div className="saka-section"><SectionHead title="Choose a window" /><div className="saka-list">{windows.map((item, i) => { const Icon = item.icon; return <button key={item.time} className="saka-list-row" onClick={() => setActive(i)} style={{ padding: "12px 10px", border: active === i ? "1px solid rgba(215,169,101,.35)" : "1px solid transparent", borderRadius: 14, background: active === i ? "rgba(215,169,101,.08)" : "transparent", textAlign: "left", color: "inherit" }}><span style={{ display: "grid", placeItems: "center", width: 31, height: 31, borderRadius: 10, background: `${item.color}18`, color: item.color }}><Icon size={15} /></span><span style={{ flex: 1 }}><span className="saka-caption" style={{ display: "block" }}>{item.time}</span><strong style={{ display: "block", marginTop: 2, fontSize: 12, fontWeight: 500 }}>{item.name}</strong></span>{active === i && <span className="saka-caption" style={{ color: "var(--saka-gold)" }}>NOW</span>}</button> })}</div></div>
    <GlassCard className="saka-section"><div className="saka-row"><div><p className="saka-eyebrow" style={{ marginBottom: 5 }}>YOUR WINDOW</p><h2 style={{ margin: 0, fontSize: 17, fontWeight: 500 }}>{current.time}</h2></div><Clock size={17} color="var(--saka-gold)" /></div><p className="saka-subtle" style={{ margin: "10px 0 15px" }}>{current.note}</p><button className="saka-button violet small" onClick={() => window.alert(`${current.name} is saved to your day.`)}><MoveRight size={14} style={{ verticalAlign: "middle", marginRight: 5 }} />Use this window</button></GlassCard>
  </SakaShell>;
}
export default DayMap;