import { Activity, ChevronRight, CircleHelp, Layers3, Sparkles, SunMedium } from "lucide-react";
import { CurveChart, GlassCard, Metric, SakaShell, SectionHead, TopBar } from "./_shared/SakaShared";
import "./_group.css";
import { useState } from "react";

const themes = [{ name: "Opportunity", value: "82%", color: "var(--saka-gold)", note: "Doors open when you make the first move." }, { name: "Communication", value: "78%", color: "var(--saka-mint)", note: "Say the simple thing, without softening it." }, { name: "Change", value: "71%", color: "var(--saka-violet-bright)", note: "A small shift changes the shape of the week." }, { name: "Relationship", value: "64%", color: "var(--saka-rose)", note: "Listen for what is underneath the words." }];
export function Forecast() {
  const [tab, setTab] = useState("Themes");
  const [selected, setSelected] = useState(0);
  return <SakaShell active="forecast"><TopBar eyebrow="14 — 20 May" title="Your forecast" back />
    <div className="saka-segmented">{["Themes", "Events", "Day map"].map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "Themes" ? <><div className="saka-section"><GlassCard><div className="saka-row"><div><p className="saka-eyebrow" style={{ marginBottom: 4 }}>THIS WEEK</p><h2 className="saka-serif" style={{ margin: 0, fontSize: 23, fontWeight: 500 }}>Make room for the new</h2></div><Sparkles size={18} color="var(--saka-gold)" /></div><p className="saka-subtle" style={{ margin: "12px 0 18px" }}>Your strongest current is moving outward. Choose the conversation, invitation, or idea that feels a little bigger than usual.</p><div className="saka-row saka-caption"><span>MON</span><span>WED</span><span>FRI</span><span>SUN</span></div><CurveChart /></GlassCard></div>
      <div className="saka-section"><SectionHead title="What is shaping the week" /><div className="saka-list">{themes.map((theme, i) => <button key={theme.name} className="saka-list-row" onClick={() => setSelected(i)} style={{ width: "100%", border: 0, textAlign: "left", color: "inherit", background: selected === i ? "rgba(195,145,223,.09)" : "none", borderRadius: 12, padding: "12px 8px" }}><span className="saka-dot" style={{ background: theme.color, boxShadow: `0 0 10px ${theme.color}` }} /><span style={{ flex: 1 }}><strong style={{ display: "block", fontSize: 12, fontWeight: 500 }}>{theme.name}</strong><span className="saka-caption">{theme.note}</span></span><b className="saka-mono" style={{ color: theme.color, fontSize: 12 }}>{theme.value}</b><ChevronRight size={14} color="var(--saka-dim)" /></button>)}</div></div>
      <div className="saka-section"><SectionHead title="Possible developments" /><GlassCard pad={false}><div style={{ padding: "3px 17px" }}>{["Important communication", "New opportunity", "Delay in plans", "Conflict / disagreement"].map((t, i) => <div className="saka-list-row" key={t}><span className="saka-mono" style={{ width: 29, color: i < 2 ? "var(--saka-gold)" : "var(--saka-dim)", fontSize: 12 }}>{[72, 61, 38, 24][i]}%</span><span style={{ flex: 1, fontSize: 12 }}>{t}</span><Activity size={14} color={i < 2 ? "var(--saka-mint)" : "var(--saka-dim)"} /></div>)}</div></GlassCard></div>
    </> : <div className="saka-section"><GlassCard><div style={{ textAlign: "center", padding: "22px 0" }}>{tab === "Events" ? <SunMedium size={27} color="var(--saka-gold)" /> : <Layers3 size={27} color="var(--saka-violet-bright)" />}<h2 className="saka-serif" style={{ margin: "14px 0 6px", fontSize: 22 }}>{tab === "Events" ? "Nothing is fixed" : "Your day, in windows"}</h2><p className="saka-subtle" style={{ maxWidth: 230, margin: "0 auto 18px" }}>{tab === "Events" ? "Saka will surface important moments as they become clearer." : "See when to begin, connect, make, and restore."}</p><button className="saka-button ghost small" onClick={() => window.alert("This view is ready for your next signal.")}>Explore {tab.toLowerCase()} <CircleHelp size={13} style={{ verticalAlign: "middle", marginLeft: 4 }} /></button></div></GlassCard></div>}
  </SakaShell>;
}
export default Forecast;