import { ArrowRight, BookOpen, Brain, HeartPulse, Sparkles, TrendingUp } from "lucide-react";
import { GlassCard, MiniLotus, SakaShell, SectionHead, TopBar } from "./_shared/SakaShared";
import "./_group.css";
import { useState } from "react";

const insightData = [
  { icon: Brain, tag: "FOCUS", title: "You perform best when you focus on one important thing at a time.", detail: "Your clearest days have a single anchor. Everything else works better around it.", color: "var(--saka-violet-bright)" },
  { icon: HeartPulse, tag: "RELATIONSHIPS", title: "You tend to delay important conversations until the feeling is perfectly formed.", detail: "Try naming the first true sentence. Clarity often arrives after you begin.", color: "var(--saka-rose)" },
  { icon: TrendingUp, tag: "MOMENTUM", title: "Your energy is highest in the first half of the day.", detail: "Use the morning for decisions. Save admin for when your attention softens.", color: "var(--saka-gold)" },
];
export function Insights() {
  const [period, setPeriod] = useState("Today");
  const [open, setOpen] = useState<number | null>(0);
  return <SakaShell active="you"><TopBar eyebrow="A mirror, not a verdict" title="Insights" back /><div className="saka-segmented">{["Today", "Week", "Month", "Year"].map(item => <button key={item} className={period === item ? "active" : ""} onClick={() => setPeriod(item)}>{item}</button>)}</div><div className="saka-card saka-card-pad" style={{ marginTop: 18, textAlign: "center" }}><MiniLotus /><p className="saka-eyebrow" style={{ margin: "8px 0 7px" }}>{period.toUpperCase()}S QUIET SIGNAL</p><h2 className="saka-serif" style={{ maxWidth: 260, margin: "0 auto", fontSize: 23, lineHeight: 1.2, fontWeight: 500 }}>Your attention is a form of care.</h2><p className="saka-subtle" style={{ maxWidth: 250, margin: "10px auto 0" }}>When you give it fully, you make room for the right things to find you.</p></div><div className="saka-section"><SectionHead title="Other insights" action="View all" /><div className="saka-list">{insightData.map((insight, i) => { const Icon = insight.icon; return <button key={insight.tag} onClick={() => setOpen(open === i ? null : i)} style={{ border: 0, padding: 0, textAlign: "left", color: "inherit", background: "transparent" }}><GlassCard><div className="saka-row" style={{ alignItems: "flex-start" }}><span style={{ display: "grid", placeItems: "center", width: 31, height: 31, borderRadius: 10, color: insight.color, background: `${insight.color}16` }}><Icon size={15} /></span><span style={{ flex: 1, paddingLeft: 10 }}><span className="saka-eyebrow" style={{ display: "block", margin: "3px 0 8px", color: insight.color }}>{insight.tag}</span><strong style={{ display: "block", fontSize: 13, lineHeight: 1.43, fontWeight: 500 }}>{insight.title}</strong></span><ArrowRight size={14} color="var(--saka-dim)" /></div>{open === i && <p className="saka-subtle" style={{ margin: "14px 0 0", paddingTop: 13, borderTop: "1px solid var(--saka-line)" }}>{insight.detail}</p>}</GlassCard></button> })}</div></div><GlassCard className="saka-section"><div className="saka-row"><div><p className="saka-eyebrow" style={{ marginBottom: 4 }}>KEEP A THREAD</p><h3 style={{ margin: 0, fontSize: 15, fontWeight: 500 }}>What did you notice today?</h3></div><BookOpen size={16} color="var(--saka-gold)" /></div><button className="saka-button ghost small" style={{ marginTop: 14 }} onClick={() => window.alert("Reflection saved. Saka will look for the thread.")}><Sparkles size={13} style={{ verticalAlign: "middle", marginRight: 5 }} />Add a reflection</button></GlassCard></SakaShell>;
}
export default Insights;