import { ArrowUpRight, Edit3, Fingerprint, MapPin, ShieldCheck, Sparkles } from "lucide-react";
import { GlassCard, SakaShell, TopBar } from "./_shared/SakaShared";
import "./_group.css";
import { useState } from "react";

const tabs = ["Profile", "Patterns", "Goals", "Values"];
export function Profile() {
  const [tab, setTab] = useState("Profile");
  const [editing, setEditing] = useState(false);
  return <SakaShell active="you"><TopBar title="You" notification /><div className="saka-segmented">{tabs.map(item => <button key={item} className={tab === item ? "active" : ""} onClick={() => setTab(item)}>{item}</button>)}</div>
    {tab === "Profile" ? <><div className="saka-card saka-card-pad" style={{ marginTop: 18 }}><div style={{ display: "flex", alignItems: "center", gap: 15 }}><div className="saka-avatar">AS</div><div style={{ flex: 1 }}><h2 style={{ margin: "0 0 4px", fontSize: 18, fontWeight: 500 }}>Aarav Sharma</h2><p className="saka-caption" style={{ margin: 0 }}><MapPin size={11} style={{ verticalAlign: "middle", marginRight: 3 }} />Delhi, India · 28 years</p></div><button className="saka-icon-button" onClick={() => setEditing(!editing)} aria-label="Edit profile"><Edit3 size={14} /></button></div>{editing && <div className="saka-toast">Profile details are ready to edit in your account settings.</div>}</div><div className="saka-section"><h2 className="saka-section-title" style={{ marginBottom: 12 }}>Your essence</h2><GlassCard><div className="saka-chip-row">{["Independent", "Deep thinker", "Ambitious", "Empathetic", "Creative", "Persevering"].map(item => <button className="saka-chip active" key={item} onClick={() => window.alert(`${item} is part of your essence.`)}>{item}</button>)}</div></GlassCard></div><div className="saka-section"><h2 className="saka-section-title" style={{ marginBottom: 12 }}>What drives you</h2><GlassCard pad={false}><div style={{ padding: "3px 17px" }}>{["Making a meaningful impact", "Financial freedom", "Strong relationships", "Personal growth"].map((item, i) => <div className="saka-list-row" key={item}><span className="saka-mono" style={{ color: "var(--saka-gold)", width: 21 }}>0{i + 1}</span><span style={{ flex: 1, fontSize: 12 }}>{item}</span><ArrowUpRight size={14} color="var(--saka-dim)" /></div>)}</div></GlassCard></div><GlassCard className="saka-section"><div className="saka-row"><div><p className="saka-eyebrow" style={{ marginBottom: 4 }}>A LITTLE MORE YOU</p><h3 style={{ margin: 0, fontSize: 15, fontWeight: 500 }}>Your personal signals</h3></div><Sparkles size={16} color="var(--saka-gold)" /></div><p className="saka-subtle" style={{ margin: "9px 0 13px" }}>Add context and Saka's reflections become more specific to your life.</p><button className="saka-button violet small" onClick={() => window.alert("Personal signals are ready to add.")}>Add a signal</button></GlassCard></> : <div className="saka-section"><GlassCard><div style={{ textAlign: "center", padding: "12px 5px" }}><Fingerprint size={28} color="var(--saka-violet-bright)" /><h2 className="saka-serif" style={{ margin: "13px 0 7px", fontSize: 22 }}>Your {tab.toLowerCase()}</h2><p className="saka-subtle" style={{ margin: "0 auto 17px", maxWidth: 245 }}>Saka is learning the shape of this part of your life. Add a note whenever something feels true.</p><button className="saka-button ghost small" onClick={() => window.alert(`Add your first ${tab.toLowerCase()} note.`)}>Add a note</button></div></GlassCard></div>}
    <div className="saka-section" style={{ display: "flex", justifyContent: "center", gap: 6, alignItems: "center" }}><ShieldCheck size={13} color="var(--saka-mint)" /><span className="saka-caption">Your personal details stay yours</span></div>
  </SakaShell>;
}
export default Profile;