// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/saka-mobile/AskSaka.tsx": () => import("../components/mockups/saka-mobile/AskSaka.tsx"),
  "./components/mockups/saka-mobile/DayMap.tsx": () => import("../components/mockups/saka-mobile/DayMap.tsx"),
  "./components/mockups/saka-mobile/Forecast.tsx": () => import("../components/mockups/saka-mobile/Forecast.tsx"),
  "./components/mockups/saka-mobile/Home.tsx": () => import("../components/mockups/saka-mobile/Home.tsx"),
  "./components/mockups/saka-mobile/Insights.tsx": () => import("../components/mockups/saka-mobile/Insights.tsx"),
  "./components/mockups/saka-mobile/LifeMap.tsx": () => import("../components/mockups/saka-mobile/LifeMap.tsx"),
  "./components/mockups/saka-mobile/Profile.tsx": () => import("../components/mockups/saka-mobile/Profile.tsx"),
  "./components/mockups/saka-mobile/Settings.tsx": () => import("../components/mockups/saka-mobile/Settings.tsx")
};
